name: bitronet_attendance
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  get: 5.0.0-release-candidate-6
  dartz: ^0.10.1
  dio: ^5.4.2+1
  loading_animation_widget: ^1.2.1
  gap: ^3.0.1
  smooth_page_indicator: ^1.1.0
  pinput: ^4.0.0
  email_validator: ^2.1.17
  get_secure_storage: ^1.0.4
  lucide_icons: ^0.257.0
  shimmer: ^3.0.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  persian_number_utility: ^1.1.4
  file_picker: ^8.0.2
  image_picker: ^1.1.0
  mime: ^1.0.5
  flutter_html: ^3.0.0-beta.2
  flutter_image_compress: ^2.2.0
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  persian_datetime_picker: ^2.6.0
  custom_clippers: ^2.0.0
  animate_do: ^3.3.4
  sliding_up_panel2: ^3.3.0+1
  card_banner: ^0.0.1+2
  infinite_scroll_pagination: ^4.0.0
  flutter_svg: ^2.0.10+1
  dotted_border: ^2.1.0
  circle_progress_bar: ^0.1.2
  carousel_slider: ^4.2.1
  visibility_detector: ^0.4.0+2
  device_info_plus: ^10.1.2
  permission_handler: ^11.3.1
  flutter_barcode_scanner: ^2.0.0
  barcode_scan2: ^4.3.3
  flex_color_scheme: ^7.3.1
  flutter_keyboard_visibility: ^6.0.0
  octo_image: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  assets:
    - assets/images/

  fonts:
    - family: Kalameh
      fonts:
        - asset: assets/font/Kalameh(FaNum)-Black.ttf
        - asset: assets/font/Kalameh(FaNum)-Bold.ttf
        - asset: assets/font/Kalameh(FaNum)-ExtraBold.ttf
        - asset: assets/font/Kalameh(FaNum)-ExtraLight.ttf
        - asset: assets/font/Kalameh(FaNum)-Light.ttf
        - asset: assets/font/Kalameh(FaNum)-Medium.ttf
        - asset: assets/font/Kalameh(FaNum)-Regular.ttf
        - asset: assets/font/Kalameh(FaNum)-SemiBold.ttf
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
