// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   // static const FirebaseOptions web = FirebaseOptions(
//   //   apiKey: 'AIzaSyChh7AzThW20V0Pi1-mAKwF87qsjPSJhN8',
//   //   appId: '1:413589492306:web:8301837576f08d6ce3058b',
//   //   messagingSenderId: '413589492306',
//   //   projectId: 'avalpardakht-255db',
//   //   authDomain: 'avalpardakht-255db.firebaseapp.com',
//   //   storageBucket: 'avalpardakht-255db.appspot.com',
//   //   measurementId: 'G-NN6D8V9LK3',
//   // );
//   //
//   // static const FirebaseOptions android = FirebaseOptions(
//   //   apiKey: 'AIzaSyCx9el3JGox-k2IgfNRmBxMA4dIqV5HaME',
//   //   appId: '1:413589492306:android:59f20ece53ae269ce3058b',
//   //   messagingSenderId: '413589492306',
//   //   projectId: 'avalpardakht-255db',
//   //   storageBucket: 'avalpardakht-255db.appspot.com',
//   // );
//   //
//   // static const FirebaseOptions ios = FirebaseOptions(
//   //   apiKey: 'AIzaSyAeUhxAzsjSwJzlQP1Ll7cOPRJ6cV2olwM',
//   //   appId: '1:413589492306:ios:bbc5aa4677a55c42e3058b',
//   //   messagingSenderId: '413589492306',
//   //   projectId: 'avalpardakht-255db',
//   //   storageBucket: 'avalpardakht-255db.appspot.com',
//   //   iosBundleId: 'com.avalpardakht.app',
//   // );
//   //
//   // static const FirebaseOptions macos = FirebaseOptions(
//   //   apiKey: 'AIzaSyAeUhxAzsjSwJzlQP1Ll7cOPRJ6cV2olwM',
//   //   appId: '1:413589492306:ios:6e576d2516cc44d3e3058b',
//   //   messagingSenderId: '413589492306',
//   //   projectId: 'avalpardakht-255db',
//   //   storageBucket: 'avalpardakht-255db.appspot.com',
//   //   iosBundleId: 'com.example.avalpardakhtFlutter',
//   // );
//   //
//   // static const FirebaseOptions windows = FirebaseOptions(
//   //   apiKey: 'AIzaSyChh7AzThW20V0Pi1-mAKwF87qsjPSJhN8',
//   //   appId: '1:413589492306:web:3f901b1473c1fecae3058b',
//   //   messagingSenderId: '413589492306',
//   //   projectId: 'avalpardakht-255db',
//   //   authDomain: 'avalpardakht-255db.firebaseapp.com',
//   //   storageBucket: 'avalpardakht-255db.appspot.com',
//   //   measurementId: 'G-LW24ZSMY2T',
//   // );
// }
