class LocalBankModel {
  int code;
  String name;
  String logo;
  String rgb;
  String enAlias;
  bool isPng;

  LocalBankModel({
    required this.code,
    required this.name,
    required this.logo,
    required this.rgb,
    required this.enAlias,
    this.isPng = false,
  });

  static List<LocalBankModel> getBankList = [
    LocalBankModel(
      code: 603799,
      name: 'بانک ملی ایران',
      logo: 'melli-22.svg',
      rgb: 'rgb(223,200,171)',
      enAlias: 'MELLI',
    ),
    LocalBankModel(
      code: 589210,
      name: 'بانک سپه',
      logo: 'sepah-24.svg',
      rgb: 'rgb(26,94,192)',
      enAlias: 'SEPAH',
    ),
    LocalBankModel(
      code: 636949,
      name: 'بانک سپه',
      logo: 'sepah-24.svg',
      rgb: 'rgb(26,94,192)',
      enAlias: 'SEPAH',
    ),
    LocalBankModel(
      code: 639370,
      name: 'بانک سپه',
      logo: 'sepah-24.svg',
      rgb: 'rgb(26,94,192)',
      enAlias: 'SEPAH',
    ),
    LocalBankModel(
      code: 505801,
      name: 'بانک سپه',
      logo: 'sepah-24.svg',
      rgb: 'rgb(26,94,192)',
      enAlias: 'SEPAH',
    ),
    LocalBankModel(
      code: 639599,
      name: 'بانک سپه',
      logo: 'sepah-24.svg',
      rgb: 'rgb(26,94,192)',
      enAlias: 'SEPAH',
    ),
    LocalBankModel(
      code: 627381,
      name: 'بانک سپه',
      logo: 'sepah-24.svg',
      rgb: 'rgb(26,94,192)',
      enAlias: 'SEPAH',
    ),
    LocalBankModel(
      code: 603769,
      name: 'بانک صادرات ایران',
      logo: 'saderat-29.svg',
      rgb: 'rgb(45,42,104)',
      enAlias: 'SADERAT',
    ),
    LocalBankModel(
      code: 627648,
      name: 'بانک توسعه صادرات',
      logo: 'tosesaderat-18.svg',
      rgb: 'rgb(0,109,8)',
      enAlias: 'TOSESADERAT',
    ),
    LocalBankModel(
      code: 207177,
      name: 'بانک توسعه صادرات',
      logo: 'tosesaderat-18.svg',
      rgb: 'rgb(0,109,8)',
      enAlias: 'TOSESADERAT',
    ),
    LocalBankModel(
      code: 603770,
      name: 'بانک کشاورزی',
      logo: 'keshavarzi-07.svg',
      rgb: 'rgb(123,114,62)',
      enAlias: 'KESHAVARZI',
    ),
    LocalBankModel(
      code: 639217,
      name: 'بانک کشاورزی',
      logo: 'keshavarzi-07.svg',
      rgb: 'rgb(123,114,62)',
      enAlias: 'KESHAVARZI',
    ),
    LocalBankModel(
      code: 627961,
      name: 'بانک صنعت و معدن',
      logo: 'sanatmadan-16.svg',
      rgb: 'rgb(155,129,76)',
      enAlias: 'SANATMADAN',
    ),
    LocalBankModel(
      code: 628023,
      name: 'بانک مسکن',
      logo: 'maskan-26.svg',
      rgb: 'rgb(236,82,13)',
      enAlias: 'MASKAN',
    ),
    LocalBankModel(
      code: 627760,
      name: 'پست بانک ایران',
      logo: 'post-09.svg',
      rgb: 'rgb(20,118,62)',
      enAlias: 'POSTBANK',
    ),
    LocalBankModel(
      code: 502908,
      name: 'بانک توسعه تعاون',
      logo: 'tosetaavon-19.svg',
      rgb: 'rgb(104,183,207)',
      enAlias: 'TAAVON',
    ),
    LocalBankModel(
      code: 622106,
      name: 'بانک پارسیان',
      logo: 'parsian-21.svg',
      rgb: 'rgb(132,93,62)',
      enAlias: 'PARSIAN',
    ),
    LocalBankModel(
      code: 639194,
      name: 'بانک پارسیان',
      logo: 'parsian-21.svg',
      rgb: 'rgb(132,93,62)',
      enAlias: 'PARSIAN',
    ),
    LocalBankModel(
      code: 627884,
      name: 'بانک پارسیان',
      logo: 'parsian-21.svg',
      rgb: 'rgb(132,93,62)',
      enAlias: 'PARSIAN',
    ),
    LocalBankModel(
      code: 502229,
      name: 'بانک پاسارگاد',
      logo: 'pasargad-10.svg',
      rgb: 'rgb(254,204,9)',
      enAlias: 'PASARGAD',
    ),
    LocalBankModel(
      code: 639347,
      name: 'بانک پاسارگاد',
      logo: 'pasargad-10.svg',
      rgb: 'rgb(254,204,9)',
      enAlias: 'PASARGAD',
    ),
    LocalBankModel(
      code: 627488,
      name: 'بانک کارآفرین',
      logo: 'karafarin-06.svg',
      rgb: 'rgb(98,115,38)',
      enAlias: 'KARAFARIN',
    ),
    LocalBankModel(
      code: 502910,
      name: 'بانک کارآفرین',
      logo: 'karafarin-06.svg',
      rgb: 'rgb(98,115,38)',
      enAlias: 'KARAFARIN',
    ),
    LocalBankModel(
      code: 621986,
      name: 'بانک سامان',
      logo: 'saman-01.svg',
      rgb: 'rgb(100,186,231)',
      enAlias: 'SAMAN',
    ),
    LocalBankModel(
      code: 639346,
      name: 'بانک سینا',
      logo: 'sina-23.svg',
      rgb: 'rgb(83,132,171)',
      enAlias: 'SINA',
    ),
    LocalBankModel(
      code: 639607,
      name: 'بانک سرمایه',
      logo: 'sarmaye-17.svg',
      rgb: 'rgb(128,130,135)',
      enAlias: 'SARMAYEH',
    ),
    LocalBankModel(
      code: 502806,
      name: 'بانک شهر',
      logo: 'shahr-25.svg',
      rgb: 'rgb(216,38,44)',
      enAlias: 'SHAHR',
    ),
    LocalBankModel(
      code: 504706,
      name: 'بانک شهر',
      logo: 'shahr-25.svg',
      rgb: 'rgb(216,38,44)',
      enAlias: 'SHAHR',
    ),
    LocalBankModel(
      code: 502938,
      name: 'بانک دی',
      logo: 'day-12.svg',
      rgb: 'rgb(0,139,160)',
      enAlias: 'DAY',
    ),
    LocalBankModel(
      code: 610433,
      name: 'بانک ملت',
      logo: 'mellat-02.svg',
      rgb: 'rgb(195,67,36)',
      enAlias: 'MELLAT',
    ),
    LocalBankModel(
      code: 991975,
      name: 'بانک ملت',
      logo: 'mellat-02.svg',
      rgb: 'rgb(195,67,36)',
      enAlias: 'MELLAT',
    ),
    LocalBankModel(
      code: 585983,
      name: 'بانک تجارت',
      logo: 'tejarat-13.svg',
      rgb: 'rgb(45,74,152)',
      enAlias: 'TEJARAT',
    ),
    LocalBankModel(
      code: 627353,
      name: 'بانک تجارت',
      logo: 'tejarat-13.svg',
      rgb: 'rgb(45,74,152)',
      enAlias: 'TEJARAT',
    ),
    LocalBankModel(
      code: 589463,
      name: 'بانک رفاه کارگران',
      logo: 'refahkargaran-28.svg',
      rgb: 'rgb(23, 53, 118)',
      enAlias: 'REFAH',
    ),
    LocalBankModel(
      code: 505785,
      name: 'بانک ایران زمین',
      logo: 'Iranzamin-logo.svg',
      rgb: 'rgb(138, 42, 118)',
      enAlias: 'IRANZAMIN',
    ),
    LocalBankModel(
      code: 636795,
      name: 'بانک مرکزی',
      logo: 'bankmarkazi.svg',
      rgb: 'rgb(46,50,147)',
      enAlias: '',
    ),
    LocalBankModel(
      code: 628157,
      name: 'موسسه اعتباری توسعه',
      logo: 'tose-11.svg',
      rgb: 'rgb(143,36,38)',
      enAlias: 'TOSE',
    ),
    LocalBankModel(
      code: 505416,
      name: 'بانک گردشگری',
      logo: 'gardeshgari-20.svg',
      rgb: 'rgb(167,53,63)',
      enAlias: 'GARDESHGARI',
    ),
    LocalBankModel(
      code: 606373,
      name: 'بانک قرض الحسنه مهر ایرانیان',
      logo: 'mehriran-15.svg',
      rgb: 'rgb(32,155,28)',
      enAlias: 'MEHRIRAN',
    ),
    LocalBankModel(
      code: 636214,
      name: 'بانک آینده',
      logo: 'ayande-03.svg',
      rgb: 'rgb(162,98,31)',
      enAlias: 'AYANDEH',
    ),
    LocalBankModel(
      code: 627412,
      name: 'بانک اقتصاد نوین',
      logo: 'eghtesad-04.svg',
      rgb: 'rgb(102,40,145)',
      enAlias: 'EGHTESADNOVIN',
    ),
    LocalBankModel(
      code: 504172,
      name: 'بانک قرض الحسنه رسالت',
      logo: 'resalat.png',
      isPng: true,
      rgb: 'rgb(233,242,244)',
      enAlias: 'RESALAT',
    ),
    LocalBankModel(
      code: 507677,
      name: 'موسسه اعتباری نور',
      logo: 'noor.png',
      isPng: true,
      rgb: 'rgb(132,178,216)',
      enAlias: 'NOOR',
    ),
    LocalBankModel(
      code: 611828,
      name: 'بلو بانک',
      logo: 'blubank.png',
      isPng: true,
      rgb: 'rgb(73,136,216)',
      enAlias: 'BLUEBANK',
    ),
    LocalBankModel(
      code: 585947,
      name: 'بانک خاورمیانه',
      logo: 'khavarmiane.svg',
      rgb: 'rgb(242, 141, 25)',
      enAlias: 'MIDDLEEAST',
    ),
  ];

  @override
  bool operator ==(Object other) => (other is LocalBankModel) && other.name == name;
}
